import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMail,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import backend_photo from "../public/backend-1.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import anime_logo from "../public/anime-logo.png";
import Tic_Tac_Toe from "../public/Tic_Tac_Toe.png";
import MARIO from "../public/MARIO.png";
import League_of_Legends from "../public/League_of_Legends.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import Link from 'next/link'; 

export default function Home() {

  const handleClickMail = () => {
    window.open("reyesjean3068@gmail.com");
  }

  const handleClickGithub = () => {
    window.open("https://github.com/jeanreye4", "_blank");
  }

  const handleClickLinked = () => {
    window.open("https://www.linkedin.com/in/jean-reyes-3027951b8/", "_blank");
  };

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jean Reyes React-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-gray-100">Hello</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-gray-100"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/18CVZC1IttUVVAerj3FmrAeNwKBoR-NuY/view?usp=share_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Jean Reyes
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">Software Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300">
              This is basically the about me section which i need to put alot of
              words for it to look good
            </p>
          </div>
          <p className="text-gray-900 dark:text-gray-100 text-2xl text-center py-6  ">How to get in contact with me</p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-900 dark:text-gray-100 ">
            <AiFillGithub
            onClick={handleClickGithub}
            />
            <AiFillLinkedin
            onClick={handleClickLinked}
            />
            <AiFillMail />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">What I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Write some text here about my journey
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={backend_photo}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">My designs</h3>
              <p className="py-2">Some random words to take up space</p>
              <h4 className="py-4 text-deal-600">Tools I used</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">My designs</h3>
              <p className="py-2">Some random words to take up space</p>
              <h4 className="py-4 text-deal-600">Tools I used</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">My designs</h3>
              <p className="py-2">Some random words to take up space</p>
              <h4 className="py-4 text-deal-600">Tools I used</h4>
              <p className="text-gray-800 py-1">photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="dark:text-white">some import text to say something</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" basis-1/3 flex-1">
              <Image
                src={anime_logo}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={Tic_Tac_Toe}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 flex justify-center items-center ">
              <Image
                src={MARIO}
                className="rounded-lg object-cover h-full"
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1">
              <Image
                src={League_of_Legends}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 flex ">
              <Image
                src={web5}
                className="rounded-lg object-cover "
                layout="responsive"
              />
            </div>
            <div className=" basis-1/3 flex-1 ">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
